name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Documentation to GitHub Pages
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install -g docusaurus

      - name: Build Script
        run: |
          ./scripts/build_docs.sh -b

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
